In [30]:
import pandas as pd
%matplotlib inline
import matplotlib.pyplot as plt
import seaborn as sns
df_08=pd.read_csv('data_08_v1.csv')
df_18=pd.read_csv('data_18_v1.csv')

In [31]:
df_08

,model,displ,cyl,trans,drive,fuel,cert_region,veh_class,air_pollution_score,city_mpg,hwy_mpg,cmb_mpg,greenhouse_gas_score,smartway
0,ACURA MDX,3.7,(6 cyl),Auto-S5,4WD,Gasoline,CA,SUV,7,15,20,17,4,no
1,ACURA MDX,3.7,(6 cyl),Auto-S5,4WD,Gasoline,FA,SUV,6,15,20,17,4,no
2,ACURA RDX,2.3,(4 cyl),Auto-S5,4WD,Gasoline,CA,SUV,7,17,22,19,5,no
3,ACURA RDX,2.3,(4 cyl),Auto-S5,4WD,Gasoline,FA,SUV,6,17,22,19,5,no
4,ACURA RL,3.5,(6 cyl),Auto-S5,4WD,Gasoline,CA,midsize car,7,16,24,19,5,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2399,VOLVO XC 90,3.2,(6 cyl),Auto-S6,4WD,Gasoline,CA,SUV,7,14,20,16,4,no
2400,VOLVO XC 90,4.4,(8 cyl),Auto-S6,4WD,Gasoline,CA,SUV,7,13,19,15,3,no
2401,VOLVO XC 90,3.2,(6 cyl),Auto-S6,2WD,Gasoline,FA,SUV,6,14,20,16,4,no
2402,VOLVO XC 90,3.2,(6 cyl),Auto-S6,4WD,Gasoline,FA,SUV,6,14,20,16,4,no
2403,VOLVO XC 90,4.4,(8 cyl),Auto-S6,4WD,Gasoline,FA,SUV,6,13,19,15,3,no

In [32]:
df_18

,model,displ,cyl,trans,drive,fuel,cert_region,veh_class,air_pollution_score,city_mpg,hwy_mpg,cmb_mpg,greenhouse_gas_score,smartway
0,ACURA RDX,3.5,6.0,SemiAuto-6,2WD,Gasoline,FA,small SUV,3,20,28,23,5,No
1,ACURA RDX,3.5,6.0,SemiAuto-6,2WD,Gasoline,CA,small SUV,3,20,28,23,5,No
2,ACURA RDX,3.5,6.0,SemiAuto-6,4WD,Gasoline,FA,small SUV,3,19,27,22,4,No
3,ACURA RDX,3.5,6.0,SemiAuto-6,4WD,Gasoline,CA,small SUV,3,19,27,22,4,No
4,ACURA TLX,2.4,4.0,AMS-8,2WD,Gasoline,CA,small car,3,23,33,27,6,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1606,VOLVO XC 90,2.0,4.0,SemiAuto-8,4WD,Gasoline,FA,standard SUV,5,22,28,24,5,No
1607,VOLVO XC 90,2.0,4.0,SemiAuto-8,4WD,Gasoline,CA,standard SUV,5,20,27,23,5,No
1608,VOLVO XC 90,2.0,4.0,SemiAuto-8,4WD,Gasoline,FA,standard SUV,5,20,27,23,5,No
1609,VOLVO XC 90,2.0,4.0,SemiAuto-8,4WD,Gasoline/Electricity,CA,standard SUV,7,26/63,30/61,27/62,10,Elite
1610,VOLVO XC 90,2.0,4.0,SemiAuto-8,4WD,Gasoline/Electricity,FA,standard SUV,7,26/63,30/61,27/62,10,Elite

In [33]:
df_08.shape

(2404, 14)

In [34]:
df_18.shape

(1611, 14)

In [36]:
df_08=df_08.query('cert_region =="CA"')
df_08

,model,displ,cyl,trans,drive,fuel,cert_region,veh_class,air_pollution_score,city_mpg,hwy_mpg,cmb_mpg,greenhouse_gas_score,smartway
0,ACURA MDX,3.7,(6 cyl),Auto-S5,4WD,Gasoline,CA,SUV,7,15,20,17,4,no
2,ACURA RDX,2.3,(4 cyl),Auto-S5,4WD,Gasoline,CA,SUV,7,17,22,19,5,no
4,ACURA RL,3.5,(6 cyl),Auto-S5,4WD,Gasoline,CA,midsize car,7,16,24,19,5,no
6,ACURA TL,3.2,(6 cyl),Auto-S5,2WD,Gasoline,CA,midsize car,7,18,26,21,6,yes
7,ACURA TL,3.5,(6 cyl),Auto-S5,2WD,Gasoline,CA,midsize car,7,17,26,20,6,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2394,VOLVO V70,3.2,(6 cyl),Auto-S6,2WD,Gasoline,CA,station wagon,7,16,24,19,5,no
2396,VOLVO XC 70,3.2,(6 cyl),Auto-S6,4WD,Gasoline,CA,SUV,7,15,22,17,4,no
2398,VOLVO XC 90,3.2,(6 cyl),Auto-S6,2WD,Gasoline,CA,SUV,7,14,20,16,4,no
2399,VOLVO XC 90,3.2,(6 cyl),Auto-S6,4WD,Gasoline,CA,SUV,7,14,20,16,4,no
2400,VOLVO XC 90,4.4,(8 cyl),Auto-S6,4WD,Gasoline,CA,SUV,7,13,19,15,3,no

In [37]:
df_08.shape

(1084, 14)

In [38]:
df_08['cert_region'].unique()

array(['CA'], dtype=object)

In [40]:
df_18=df_18.query('cert_region =="CA"')
df_18

,model,displ,cyl,trans,drive,fuel,cert_region,veh_class,air_pollution_score,city_mpg,hwy_mpg,cmb_mpg,greenhouse_gas_score,smartway
1,ACURA RDX,3.5,6.0,SemiAuto-6,2WD,Gasoline,CA,small SUV,3,20,28,23,5,No
3,ACURA RDX,3.5,6.0,SemiAuto-6,4WD,Gasoline,CA,small SUV,3,19,27,22,4,No
4,ACURA TLX,2.4,4.0,AMS-8,2WD,Gasoline,CA,small car,3,23,33,27,6,No
6,ACURA TLX,3.5,6.0,SemiAuto-9,2WD,Gasoline,CA,small car,3,20,32,24,5,No
8,ACURA TLX,3.5,6.0,SemiAuto-9,4WD,Gasoline,CA,small car,3,21,30,24,5,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1601,VOLVO XC 60,2.0,4.0,SemiAuto-8,4WD,Gasoline/Electricity,CA,small SUV,7,26/60,28/58,26/59,10,Elite
1603,VOLVO XC 90,2.0,4.0,SemiAuto-8,2WD,Gasoline,CA,standard SUV,5,22,29,25,5,No
1605,VOLVO XC 90,2.0,4.0,SemiAuto-8,4WD,Gasoline,CA,standard SUV,5,22,28,24,5,No
1607,VOLVO XC 90,2.0,4.0,SemiAuto-8,4WD,Gasoline,CA,standard SUV,5,20,27,23,5,No
1609,VOLVO XC 90,2.0,4.0,SemiAuto-8,4WD,Gasoline/Electricity,CA,standard SUV,7,26/63,30/61,27/62,10,Elite

In [41]:
df_18['cert_region'].unique()

array(['CA'], dtype=object)

In [43]:
df_08.drop('cert_region', axis=1, inplace=True)
df_18.drop('cert_region', axis=1, inplace=True)

In [44]:
df_08

,model,displ,cyl,trans,drive,fuel,veh_class,air_pollution_score,city_mpg,hwy_mpg,cmb_mpg,greenhouse_gas_score,smartway
0,ACURA MDX,3.7,(6 cyl),Auto-S5,4WD,Gasoline,SUV,7,15,20,17,4,no
2,ACURA RDX,2.3,(4 cyl),Auto-S5,4WD,Gasoline,SUV,7,17,22,19,5,no
4,ACURA RL,3.5,(6 cyl),Auto-S5,4WD,Gasoline,midsize car,7,16,24,19,5,no
6,ACURA TL,3.2,(6 cyl),Auto-S5,2WD,Gasoline,midsize car,7,18,26,21,6,yes
7,ACURA TL,3.5,(6 cyl),Auto-S5,2WD,Gasoline,midsize car,7,17,26,20,6,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2394,VOLVO V70,3.2,(6 cyl),Auto-S6,2WD,Gasoline,station wagon,7,16,24,19,5,no
2396,VOLVO XC 70,3.2,(6 cyl),Auto-S6,4WD,Gasoline,SUV,7,15,22,17,4,no
2398,VOLVO XC 90,3.2,(6 cyl),Auto-S6,2WD,Gasoline,SUV,7,14,20,16,4,no
2399,VOLVO XC 90,3.2,(6 cyl),Auto-S6,4WD,Gasoline,SUV,7,14,20,16,4,no
2400,VOLVO XC 90,4.4,(8 cyl),Auto-S6,4WD,Gasoline,SUV,7,13,19,15,3,no

In [47]:
df_08.shape

(1084, 13)

In [46]:
df_18.shape

(798, 13)

In [53]:
df_08.isnull().sum()

model                    0
displ                    0
cyl                     75
trans                   75
drive                   37
fuel                     0
veh_class                0
air_pollution_score      0
city_mpg                75
hwy_mpg                 75
cmb_mpg                 75
greenhouse_gas_score    75
smartway                 0
dtype: int64

In [55]:
df_18.isnull().sum()

model                   0
displ                   1
cyl                     1
trans                   0
drive                   0
fuel                    0
veh_class               0
air_pollution_score     0
city_mpg                0
hwy_mpg                 0
cmb_mpg                 0
greenhouse_gas_score    0
smartway                0
dtype: int64

In [56]:
df_08.dropna(inplace=True)
df_18.dropna(inplace=True)

In [60]:
df_08.isnull().sum()

model                   0
displ                   0
cyl                     0
trans                   0
drive                   0
fuel                    0
veh_class               0
air_pollution_score     0
city_mpg                0
hwy_mpg                 0
cmb_mpg                 0
greenhouse_gas_score    0
smartway                0
dtype: int64

In [61]:
df_18.isnull().sum()

model                   0
displ                   0
cyl                     0
trans                   0
drive                   0
fuel                    0
veh_class               0
air_pollution_score     0
city_mpg                0
hwy_mpg                 0
cmb_mpg                 0
greenhouse_gas_score    0
smartway                0
dtype: int64

In [63]:
sum(df_18.duplicated())

3

In [65]:
sum(df_08.duplicated())

23

In [70]:
df_08.drop_duplicates(inplace=True)
df_18.drop_duplicates(inplace=True)

In [72]:
print(sum(df_08.duplicated()))
print(sum(df_18.duplicated()))

0
0

In [73]:
df_08.to_csv('data_08_v2.csv', index=False)
df_18.to_csv('data_18_v2.csv', index=False)

In [77]:
df_08.shape

(986, 13)

In [78]:
df_18.shape

(794, 13)

In [79]:
df_08.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 986 entries, 0 to 2400
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   model                 986 non-null    object
 1   displ                 986 non-null    float64
 2   cyl                   986 non-null    object
 3   trans                 986 non-null    object
 4   drive                 986 non-null    object
 5   fuel                  986 non-null    object
 6   veh_class             986 non-null    object
 7   air_pollution_score   986 non-null    object
 8   city_mpg              986 non-null    object
 9   hwy_mpg               986 non-null    object
 10  cmb_mpg               986 non-null    object
 11  greenhouse_gas_score  986 non-null    object
 12  smartway              986 non-null    object
dtypes: float64(1), object(12)
memory usage: 107.8+ KB

In [80]:
df_18.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 794 entries, 1 to 1609
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   model                 794 non-null    object
 1   displ                 794 non-null    float64
 2   cyl                   794 non-null    float64
 3   trans                 794 non-null    object
 4   drive                 794 non-null    object
 5   fuel                  794 non-null    object
 6   veh_class             794 non-null    object
 7   air_pollution_score   794 non-null    int64
 8   city_mpg              794 non-null    object
 9   hwy_mpg               794 non-null    object
 10  cmb_mpg               794 non-null    object
 11  greenhouse_gas_score  794 non-null    int64
 12  smartway              794 non-null    object
dtypes: float64(2), int64(2), object(9)
memory usage: 86.8+ KB